name: CI

on:
  push

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    
  resume:
    runs-on: ubuntu-latest
    steps:
        - name: resume
          if: always()
          run: |
            echo "This is the resume job"
            echo "## Results" >> "$GITHUB_STEP_SUMMARY"
            echo " " >> "$GITHUB_STEP_SUMMARY"
            echo "Tests completed with status: ${{ job.status }}" >> "$GITHUB_STEP_SUMMARY"