name: CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  resume:
    runs-on: ubuntu-latest
    steps:
        - name: resume
          if: always()
          run: |
            echo "This is the resume job"
            echo "## Results" > resume.md
            echo "### Tests" >> resume.md
            if [ ${{ job.status }} == 'success' ]; then
              echo "- All tests passed" >> resume.md
            else
              echo "- Some tests failed" >> resume.md
            fi
            echo "### Linting" >> resume.md
            if [ ${{ job.status }} == 'success' ]; then
              echo "- Linting passed" >> resume.md
            else
              echo "- Linting failed" >> resume.md
            fi
            echo "### Formatting" >> resume.md
            if [ ${{ job.status }} == 'success' ]; then
              echo "- Formatting passed" >> resume.md
            else
              echo "- Formatting failed" >> resume.md            fi
            cat resume.md      